apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-cluster-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-1-store
    kind: ClusterSecretStore 
  target:
    name: cluster-1-k8-secret
    creationPolicy: Owner
  data:
  - secretKey: k8-cluster-1-user
    remoteRef:
      key: credentials_secret-vpc-a-tll6
      property: user
  - secretKey: k8-cluster-1-password
    remoteRef:
      key: credentials_secret-vpc-a-tll6
      property: password

###### result
# Name:         cluster-1-k8-secret
# Namespace:    default
# Labels:       <none>
# Annotations:  reconcile.external-secrets.io/data-hash: 62e029f595916a831a7988709cf1e544
# 
# Type:  Opaque
# 
# Data
# ====
# k8-cluster-1-password:  9 bytes
# k8-cluster-1-user:      5 bytes
